resources:
- name: salontimeapp
  type: git
  source:
    uri: https://github.com/renanpadilha/salontimeapp.git
    branch: master
    username: renanpadilha
    password: renancio123

jobs:
- name: build
  plan:
    - get: salontimeapp
      trigger: true
    - task: npm-install
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: digitallyseamless/nodejs-bower-grunt
        inputs:
          - name: salontimeapp
        # outputs:
        #   - name: build
        run:
          dir: salontimeapp
          path: npm
          args: ['install']
    - task: grunt-install
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: digitallyseamless/nodejs-bower-grunt
        inputs:
          - name: salontimeapp
        run:
          dir: salontimeapp
          path: npm
          args: ['install', 'grunt-cli']
    - task: bower-install
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: digitallyseamless/nodejs-bower-grunt
        inputs:
          - name: salontimeapp
        run:
          dir: salontimeapp
          path: bower
          args: ['install', '--allow-root']
    - task: check-install
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: digitallyseamless/nodejs-bower-grunt
        inputs:
          - name: salontimeapp
        run:
          path: ls
          args: ['-alR']
